
import mongoose from 'mongoose';
import GrapeTypeModel from '../modelos/type_d_grapetype';

const grapeTypes = [
    { name: 'ABUNDANTE', color: 'RED' },
    { name: 'AGLIANICO', color: 'RED' },
    { name: 'ALADASTURI', color: 'RED' },
    { name: 'ALBARIÑO', color: 'WHITE' },
    { name: 'ALBARELLO', color: 'RED' },
    { name: 'ALBARINHO TINTO', color: 'RED' },
    { name: 'ALEKSANDROULI', color: 'RED' },
    { name: 'ALFROCHEIRO PRETO', color: 'RED' },
    { name: 'ALICANTE', color: 'RED' },
    { name: 'ALICANTE BOUSCHET', color: 'RED' },
    { name: 'AMARAL', color: 'RED' },
    { name: 'AMARAL PRETO', color: 'RED' },
    { name: 'ARAMÓN', color: 'RED' },
    { name: 'ARAGONÉS', color: 'RED' },
    { name: 'ARENI NOIR', color: 'RED' },
    { name: 'AZAL', color: 'RED' },
    { name: 'AZAL PRETO', color: 'RED' },
    { name: 'AZAL TINTO', color: 'RED' },
    { name: 'BAGA', color: 'RED' },
    { name: 'BAGA DE LOURO', color: 'RED' },
    { name: 'BALAU', color: 'RED' },
    { name: 'BALAURO', color: 'RED' },
    { name: 'BARBERÁ', color: 'RED' },
    { name: 'BELLA DA CAXATA', color: 'RED' },
    { name: 'BENICARLÓ', color: 'RED' },
    { name: 'BERNACHA NEGRA', color: 'RED' },
    { name: 'BOAL', color: 'RED' },
    { name: 'BOBAL', color: 'RED' },
    { name: 'BOBAL NOIR', color: 'RED' },
    { name: 'BOBOS', color: 'RED' },
    { name: 'BOGALHAL', color: 'RED' },
    { name: 'BONICAIRE', color: 'RED' },
    { name: 'BORRAÇAL', color: 'RED' },
    { name: 'BORRACAL AZEDO', color: 'RED' },
    { name: 'BORRACO', color: 'RED' },
    { name: 'BORRASAO', color: 'RED' },
    { name: 'BORRASAO NEGRO', color: 'RED' },
    { name: 'BORDO', color: 'RED' },
    { name: 'BOUCHET', color: 'RED' },
    { name: 'BOUCHY', color: 'RED' },
    { name: 'BOUGALHAL', color: 'RED' },
    { name: 'BOVVACO', color: 'RED' },
    { name: 'BRANCELLAO', color: 'RED' },
    { name: 'BRANCELLO', color: 'RED' },
    { name: 'BRENCELLAO', color: 'RED' },
    { name: 'BRETÓN', color: 'RED' },
    { name: 'BRONCELLAO', color: 'RED' },
    { name: 'BURDEOS TINTO', color: 'RED' },
    { name: 'CABERNET FRANC', color: 'RED' },
    { name: 'CABERNET SAUVIGNON', color: 'RED' },
    { name: 'CACHINO', color: 'RED' },
    { name: 'CACHÓN', color: 'RED' },
    { name: 'CALLET', color: 'RED' },
    { name: 'CANNONADDU', color: 'RED' },
    { name: 'CANNONADDU NIEDDU', color: 'RED' },
    { name: 'CANNONAO', color: 'RED' },
    { name: 'CANNONAU', color: 'RED' },
    { name: 'CANONAZO', color: 'RED' },
    { name: 'CAPBRETÓN', color: 'RED' },
    { name: 'CARBOUET', color: 'RED' },
    { name: 'CARIGNAN D’ESPAGNE', color: 'RED' },
    { name: 'CARIGNAN ESPAGNOL', color: 'RED' },
    { name: 'CARIGNAN ROUGE', color: 'RED' },
    { name: 'CARIGNANE ROSSO', color: 'RED' },
    { name: 'CARLINA', color: 'RED' },
    { name: 'CAIÑO BRAVO', color: 'RED' },
    { name: 'CAIÑO CACHÓN', color: 'RED' },
    { name: 'CAIÑO DEL PAÍS', color: 'RED' },
    { name: 'CAIÑO GORDO', color: 'RED' },
    { name: 'CAIÑO LONGO', color: 'RED' },
    { name: 'CAIÑO REDONDO', color: 'RED' },
    { name: 'CAIÑO TINTO', color: 'RED' },
    { name: 'COREANA', color: 'RED' },
    { name: 'DOZAL', color: 'RED' },
    { name: 'EMBOLICAIRE NEGRE', color: 'RED' },
    { name: 'ESFARRAPA', color: 'RED' },
    { name: 'ESFARRAPAS', color: 'RED' },
    { name: 'ESPADEIRO REDONDO', color: 'RED' },
    { name: 'ESPAGNOL', color: 'RED' },
    { name: 'FOLLE BLANCHE DU MINERVOIS', color: 'RED' },
    { name: 'GARNACHA', color: 'RED' },
    { name: 'GARNACHA TINTORERA', color: 'RED' },
    { name: 'GARNACHO NEGRO', color: 'RED' },
    { name: 'GARNATXA PAIS', color: 'RED' },
    { name: 'GEWURSTRAMINER', color: 'WHITE' },
    { name: 'GIRÓ', color: 'RED' },
    { name: 'GIRONET', color: 'RED' },
    { name: 'GODELLO', color: 'WHITE' },
    { name: 'GRAN NEGRO', color: 'RED' },
    { name: 'GRANACCIA', color: 'RED' },
    { name: 'GRANAXA', color: 'RED' },
    { name: 'GRENACHE ROUGE', color: 'RED' },
    { name: 'LLADONER', color: 'RED' },
    { name: 'LLADONER NEGRO', color: 'RED' },
    { name: 'MACABEO', color: 'WHITE' },
    { name: 'MENCÍA', color: 'RED' },
    { name: 'MERLOT', color: 'RED' },
    { name: 'MONASTRELL', color: 'RED' },
    { name: 'MOSCATEL', color: 'WHITE' },
    { name: 'MORATÓN', color: 'RED' },
    { name: 'MORAVIO', color: 'RED' },
    { name: 'MORRACA', color: 'RED' },
    { name: 'MURRACAL', color: 'RED' },
    { name: 'NAVARRA', color: 'RED' },
    { name: 'NEGRA BLANA', color: 'RED' },
    { name: 'NEGRAL', color: 'RED' },
    { name: 'NIEDDU', color: 'RED' },
    { name: 'OIL DE CHAPAUD', color: 'RED' },
    { name: 'OLHO DE SAPO', color: 'RED' },
    { name: 'PARELLADA', color: 'WHITE' },
    { name: 'PEDRAL', color: 'RED' },
    { name: 'PENAMACOR', color: 'RED' },
    { name: 'PETIT CABERNET', color: 'RED' },
    { name: 'PETIT VIDURE', color: 'RED' },
    { name: 'PINOT GRIS', color: 'WHITE' },
    { name: 'PINOT NOIR', color: 'RED' },
    { name: 'PLANYT BRETÓN', color: 'RED' },
    { name: 'POEIRINHO', color: 'RED' },
    { name: 'PROBRETON', color: 'RED' },
    { name: 'PROVECHON', color: 'RED' },
    { name: 'RAGENO', color: 'RED' },
    { name: 'RAJENO', color: 'RED' },
    { name: 'REQUENA', color: 'RED' },
    { name: 'REQUENERA', color: 'RED' },
    { name: 'REQUENO', color: 'RED' },
    { name: 'RETAGLIAD', color: 'RED' },
    { name: 'RIESLING', color: 'WHITE' },
    { name: 'RIVESALTES', color: 'RED' },
    { name: 'ROUSILLON', color: 'RED' },
    { name: 'ROUSILLON TINTO', color: 'RED' },
    { name: 'RUFETA', color: 'RED' },
    { name: 'RUFETE', color: 'RED' },
    { name: 'SEVAGGIO', color: 'RED' },
    { name: 'SOUSAO', color: 'RED' },
    { name: 'SOUSAO GALEGO', color: 'RED' },
    { name: 'SYRAH', color: 'RED' },
    { name: 'TEMPRANILLO', color: 'RED' },
    { name: 'TERRET D’ESPAGNA', color: 'RED' },
    { name: 'TINTA CARVALHA', color: 'RED' },
    { name: 'TINTA DA BAIRRADA', color: 'RED' },
    { name: 'TINTA FEMIA', color: 'RED' },
    { name: 'TINTA FEMIA DE ALDÁN', color: 'RED' },
    { name: 'TINTA MADRID', color: 'RED' },
    { name: 'TINTA PINHEIRA', color: 'RED' },
    { name: 'TINTO ARAGONÉS', color: 'RED' },
    { name: 'TINTO DE REQUENA', color: 'RED' },
    { name: 'TINTO DE ZURRA', color: 'RED' },
    { name: 'TINTO NAVALCARNERO', color: 'RED' },
    { name: 'TINTO NAVARRO', color: 'RED' },
    { name: 'TINTO REDONDO', color: 'RED' },
    { name: 'TOCCAI ROSSO', color: 'RED' },
    { name: 'TONTO DE ZURRA', color: 'RED' },
    { name: 'UVA DI SPAGNA', color: 'RED' },
    { name: 'UVA GALLEGA', color: 'RED' },
    { name: 'VALENCIANA', color: 'RED' },
    { name: 'VALENCIANA TINTA', color: 'RED' },
    { name: 'VALENCIANA TINTO', color: 'RED' },
    { name: 'VERDEJO', color: 'WHITE' },
    { name: 'VERÓN', color: 'RED' },
    { name: 'VIDURE', color: 'RED' },
    { name: 'VINATE', color: 'RED' },
    { name: 'VIOGNER', color: 'WHITE' },
    { name: 'VIURA', color: 'WHITE' },
    { name: 'XARELÓ', color: 'WHITE' }

];

const populateGrapeTypes = async () => {
    try {
        await mongoose.connect('mongodb://mongo:27017/winer-prova');
        // await mongoose.connect('mongodb://localhost:27017/Proyecto_Winners');
        await GrapeTypeModel.insertMany(grapeTypes);
        console.log('Grape types populated successfully');
        process.exit(0);
    } catch (error) {
        console.error('Error populating grape types', error);
        process.exit(1);
    }
};

populateGrapeTypes();
